     -.--ns INFO     gpi                                ..mbed/gpi_embed.cpp:79   in set_program_name_in_venv        Did not detect Python virtual environment. Using system-wide Python interpreter
     -.--ns INFO     gpi                                ../gpi/GpiCommon.cpp:101  in gpi_print_registered_impl       VPI registered
     0.00ns INFO     cocotb                             Running on Icarus Verilog version 11.0 (stable)
     0.00ns INFO     cocotb                             Running tests with cocotb v2.0.0.dev0+6c42eef3 from /home/joseantonio/.local/lib/python3.10/site-packages/cocotb
     0.00ns WARNING  gpi                                vpi_iterate returned NULL for type vpiInstance for object NULL
     0.00ns INFO     cocotb                             Seeding Python random module with 1718650828
     0.00ns ERROR    cocotb                             cocotb testbench initialization failed. Exiting.
                                                        Traceback (most recent call last):
                                                          File "/home/joseantonio/.local/lib/python3.10/site-packages/cocotb/__init__.py", line 184, in _initialise_testbench
                                                            _initialise_testbench_(argv_)
                                                          File "/home/joseantonio/.local/lib/python3.10/site-packages/cocotb/__init__.py", line 233, in _initialise_testbench_
                                                            _setup_regression_manager()
                                                          File "/home/joseantonio/.local/lib/python3.10/site-packages/cocotb/__init__.py", line 424, in _setup_regression_manager
                                                            regression_manager.discover_tests(*modules)
                                                          File "/home/joseantonio/.local/lib/python3.10/site-packages/cocotb/regression.py", line 269, in discover_tests
                                                            mod = import_module(module_name)
                                                          File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
                                                            return _bootstrap._gcd_import(name[level:], package, level)
                                                          File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
                                                          File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
                                                          File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
                                                          File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
                                                          File "/home/joseantonio/.local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 178, in exec_module
                                                            exec(co, module.__dict__)
                                                          File "/home/joseantonio/TFM/verilog-ethernet-toqueteo/verilog-ethernet/tb/eth_mac_40g/test_eth_mac_40g.py", line 31, in <module>
                                                            from scapy.layers.l2 import Ether
                                                        ModuleNotFoundError: No module named 'scapy'
